Small updates to dome
wtgee/huntsman-pocs pull request #103
Opened 2018-12-01 04:46 UTC by wtgee

More dome changes are on the way but I accidentally was working in my `develop` branch and didn't want to disentangle so am just submitting here. :)

These are the updates that existed on the Mac from the latest run.

2018-12-02 08:06 UTC, bazkiaei approved these changes

2018-12-03 01:10 UTC, AnthonyHorton requested changes
Tidying of musca.py is fine, but need to fix the tests.

2018-12-03 01:10 UTC, AnthonyHorton commented on conf_files/huntsman.yaml
> -cameras:
Removing the camera section from the default config file seems to have broken the tests. Don't think it should, though.

2018-12-03 01:26 UTC, wtgee commented on conf_files/huntsman.yaml
> -cameras:
I'll get this fixed.  Issue here https://github.com/panoptes/POCS/issues/733

2018-12-04 10:56 UTC, wtgee commented
Closing in favor of #106

2018-12-04 10:56 UTC, closed without merging