Improve prepare cameras
wtgee/huntsman-pocs pull request #188
Opened 2020-07-15 06:50 UTC by danjampro

We now require several calls to `camera.is_ready` to return `True` consecutively in order for a camera to be considered as ready in `prepare_cameras`. This is to ensure the temperature has stabilised after cooling has been enabled.

The new argument `consecutive` specifies how many consecutive successes are required.

2020-07-18 10:17 UTC, AnthonyHorton requested changes
Looks good, though the main loop can be cleaned up a bit, and the input validation and error logging could be improved.

2020-07-18 10:17 UTC, AnthonyHorton commented on huntsman/observatory.py
> +            max_attempts = consecutive
I don't think it's good practice to silently fix an invalid argument value like this. I'd be more inclined to just raise a descriptive `ValueError` in this sort of situation, and if you are going to override the argument value instead then at the very least you should log a warning, and probably display it too (using `warnings.warn`).

2020-07-18 10:17 UTC, AnthonyHorton commented on huntsman/observatory.py
>                  time.sleep(sleep)
A more idiomatic alternative implementation:

```
ready_counts = {cam_name: 0 for cam_name in self.cameras.keys()}

for i in range(max_attempts):
    for cam_name, cam in self.cameras.items():
        if cam.is_ready:
            ready_counts[cam_name] += 1
        else:
            ready_counts[cam_name] = 0

    if all([count >= consecutive for count in ready_counts.values()]):
        # All cameras are ready so stop checking now.
        break

    time.sleep(sleep)

failed_cameras = [cam_name for cam_name, count in ready_count.items() if count < consecutive]
if failed_cameras:
    # Handle failed cameras
else:
    # All cameras ready
```

Simplifies things a bit, removing a redundant check of the loop index, replacing some explicit loops with list comprehensions, and removing some unnecessary temporary variables

2020-07-18 10:17 UTC, AnthonyHorton commented on huntsman/observatory.py
> +            msg += ", ".join(cameras_failed)
Might be useful at this point to log why the camera is not ready (temperature unstable, exposing, filterwheel or focuser not ready).

2020-07-18 15:55 UTC, wtgee reviewed
In general I'm confused as to why we need to ask the cameras if they are ready multiple times.

Seems like this should be restructured so that the method is built around how much time it wants to wait while the cameras get ready, namely a `timeout` param.

Here loosely implemented with CountdownTimer:

(`unready_cameras` is a bad name but I need more :coffee:)
```py
timer = CountdownTimer(300)  # 5 minutes
sleep_interval = 60 # Should really be a part of CountdownTimer

unready_cameras = set(self.cameras.keys())
ready_cameras = set()

while timer.expired() is False:
    for cam_name in unready_cameras():
        if self.cameras[cam_name].is_ready():
            ready_cameras.add(cam_name)
            unready_cameras.remove(cam_name)

    timer.sleep(max_sleep=sleep_interval)

# Deal with ready and unready cameras below
```

I guess my real question is why do the cameras report ready and then not ready?  Can we implement a `stable_time` or something to the cameras such that they will only report ready if they have been (and stayed=) cooled for a certain amount of time?

2020-07-18 15:55 UTC, wtgee commented on huntsman/observatory.py
> +                msg += ". Dropping them from the Observatory."
The continued `msg` is a bit weird to me. I would just have the message in the `PanError` above and not have this part of the message or have it as a separate log call.

2020-07-18 23:28 UTC, AnthonyHorton commented
Yeah, there really ought to be an Issue that explains the problem that this PR is intended to solve. This also gives you an extra feeling of achievement when you merge a PR and close an Issue at the same time...

@wtgee In short, the motivation for this is that we have observed that the ZWO cameras have a tendency to overshoot the target temperature when cooling. Consequently we ran into confusing errors where all the cameras would report ready, then when POCS moved on to taking exposures we would get errors about unstable temperatures because some of the cameras had gone straight through the target temperature and were outside the temperature tolerance on the low side. So, the aim here is to wait until the cameras are consistently reporting ready before moving on. I agree that this would be better expressed as a minimum time that they should report ready for, rather than the number of consecutive queries.

2020-07-19 00:04 UTC, wtgee commented
On Sat, Jul 18, 2020, 13:28 Anthony Horton <notifications@github.com> wrote:

> Yeah, there really ought to be an Issue that explains the problem that
> this PR is intended to solve. This also gives you an extra feeling of
> achievement when you merge a PR and close an Issue at the same time...
>
> @wtgee <https://github.com/wtgee> In short, the motivation for this is
> that we have observed that the ZWO cameras have a tendency to overshoot the
> target temperature when cooling. Consequently we ran into confusing errors
> where all the cameras would report ready, then when POCS moved on to taking
> exposures we would get errors about unstable temperatures because some of
> the cameras had gone straight through the target temperature and were
> outside the temperature tolerance on the low side. So, the aim here is to
> wait until the cameras are consistently reporting ready before moving on. I
> agree that this would be better expressed as a minimum time that they
> should report ready for, rather than the number of consecutive queries.
>
But can't we just build some kind of `settle_time` into the `is_ready`
call?

This just feels a bit hacky. If we are asking a camera if it is ready and
is reporting yes but that's not true (because it hasn't settled), then I
would prefer to fix the `is_ready` so that it's always accurate.

This would be in addition to changing the logic here to be time based.


—
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/AstroHuntsman/huntsman-pocs/pull/188#issuecomment-660557234>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAARIUESRO3P2QA7BALKSYLR4IV3JANCNFSM4O2HEIWQ>
> .
>

2020-07-19 03:34 UTC, AnthonyHorton commented
> But can't we just build some kind of `settle_time` into the `is_ready` call? This just feels a bit hacky. If we are asking a camera if it is ready and is reporting yes but that's not true (because it hasn't settled), then I would prefer to fix the `is_ready` so that it's always accurate. This would be in addition to changing the logic here to be time based. —

Yes, but it gets a bit complicated because we can't afford for every `is_ready` check to take several minutes while it confirms that the temperature of each camera is stable, in turn. `is_ready` gets accessed, at least, at the start of every exposure.

We'd need to do something like having the cameras spawn their own temperature monitoring threads to keep track of the recent temperature history so that when we access `is_temperature_stable` it can immediately confirm whether the temperature has consistently stayed within tolerance of the target temperature for the preceding n minutes.

This level of sophistication is only actually required immediately after turning the cooling on, or making a large change to the target temperature.

What Dan's doing to achieve the same effect in a method of `Observatory`instead is undeniably a bit a hack, but on the other hand it means we're only doing it when it is most needed (just after turning cooling on) and it makes it easy to do the waiting for each camera in parallel without spawning lots of threads.

2020-07-20 03:28 UTC, danjampro commented
Thanks for the comments @AnthonyHorton @wtgee. I agree the time based approach is more succinct.

I also like @AnthonyHorton's suggestion of having cameras keep track of their most recent temperature history, although this sounds like a PR for `POCS`. Does that also sound like a good idea to you @wtgee ?

2020-10-03 21:19 UTC, closed without merging