creating scripts to take manual observations - WIP
wtgee/huntsman-pocs pull request #207
Opened 2020-09-11 07:02 UTC by lspitler

2020-09-11 07:26 UTC, JAAlvarado-Montes commented on scripts/take_day_flats.py
> +            exposure_events.append(camera.take_observation(observation, filename=new_filename))
Need to add `headers={}` inside take_observation to avoid a bug in POCS.

2020-09-11 07:29 UTC, JAAlvarado-Montes requested changes
Look at the comment above, include `headers={}` to avoid POC's bug

2020-09-11 07:52 UTC, JAAlvarado-Montes requested changes
See comments above.

2020-09-11 07:52 UTC, JAAlvarado-Montes commented on scripts/take_day_flats.py
> +
Before doing `camera.take_observation`, it'll be good to move the filterwheel to the filter we want to use by using `camera.filterwheel.move_to(f'{filter_name}')`, so we need to add `filter_name` as an argument to the function `take_pics`. Currently, we have to manually move the filterwheel of each camera, thawhich could be done inside this function automatically for all the cameras.

2020-09-11 08:02 UTC, JAAlvarado-Montes commented
I have made two changes to this PR, namely added `headers={}` to avoid a current bug in POCS and added an argument called `filter_name` to move all of the filterwheels to the same slot we want to use. Please review.

Cheers!

2020-09-11 23:55 UTC, lspitler commented
Thanks @JAAlvarado-Montes for the edits. Do we need to add a function that turns on cooling for the cameras?

2020-09-12 19:23 UTC, wtgee commented
FYI, this is on hold for just a bit but all these parts will probably be incorporated.

2020-09-12 19:26 UTC, AnthonyHorton commented
Hopefully relevant to this:

https://github.com/panoptes/POCS/pull/1003 & #208

2020-09-12 19:30 UTC, AnthonyHorton commented
> I have made two changes to this PR, namely added `headers={}` to avoid a current bug in POCS...

That's a reference to this: https://github.com/panoptes/POCS/issues/1002

2020-10-28 00:48 UTC, lspitler commented
closing as this is being done in new repo `huntsman-bridge`

2020-10-28 00:48 UTC, closed without merging