DFW manual functions
wtgee/huntsman-pocs pull request #212
Opened 2020-09-15 06:36 UTC by Physarah

A set of functions to take manual observations for the dfw run.

To take science images:
```
from manual_functions import do_science_setup
import numpy as np

cam_name = 'camera.zwo.0'
filter_type = 'g'
initial_focus_position = 22266
target_name = 'FRB190711'

pocs_observation = do_science_setup(cam_name, 
                                   target_name, 
                                   initial_focus_position, 
                                   filter_type)

pocs_observation.observatory.observe()
```

2020-09-15 22:05 UTC, lspitler requested changes
@Physarah looking good. Not yet approving so can keep tweaking based upon improvements during the week. Can you incorporate what you learned last night into this file?

Also, it might just make sense to make this a script by adding the following at the bottom of the file:

```python

def main(obstype,
                cam_name, 
                target_name, 
                initial_focus_position, 
                filter_type,
                num_sciobs=1,
                ...):
    if obstype is "sci":
        pocs_observation = do_science_setup(cam_name, 
                                   target_name, 
                                   initial_focus_position, 
                                   filter_type)
        for i in range(num_sciobs):
             pocs_observation.observatory.observe()
   elif obstype is "dark":
        stuff
   elif obstype is "flat":
        stuff

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--obs-type', type=str, help='Options: sci, dark, flat.', choices=["sci", "dark", "flat"])
    parser.add_argument('--cam-name', type=str, help='Camera name in config.yaml to use.')
    parser.add_argument('--filter', type=str, help='Valid filter name.')
    parser.add_argument('--focus', type=int, help='The camera's best focus value.')
    parser.add_argument('--target', type=str, help='Target to observe in targets.yaml.')
    parser.add_argument('--num-sciobs', type=str, help='Number of science exposures to take.')
    parser.add_argument('--exptime', type=str, help='Override default exptime.')

    args = parser.parse_args()
    obstype = args.obstype

    main(meta_db_location)


```

2020-09-15 22:05 UTC, lspitler commented on scripts/dfw_manual_functions.py
> +    simulators=['weather', 'mount', 'power', 'night']
move to arg of this function

2020-09-15 22:05 UTC, lspitler commented on scripts/dfw_manual_functions.py
> +    test_observation = pocs.observatory.scheduler.observations[target_name]
rename `test_observations` as it isnt a test

2020-09-15 22:05 UTC, lspitler commented on scripts/dfw_manual_functions.py
> +    pocs.observatory.take_flat_fields(camera_names = cam_name)
This must be a list:
```suggestion
    pocs.observatory.take_flat_fields(camera_names = [cam_name])
```

2020-09-15 22:05 UTC, lspitler commented on scripts/dfw_manual_functions.py
> +    pocs.observatory.take_dark_fields(exptimes = exposure_time)
Do you need to add the arg: `camera_names = [cam_name]`?

2020-09-15 22:05 UTC, lspitler commented on scripts/dfw_manual_functions.py
> +    simulators=['weather', 'mount', 'power', 'night']
make this an arg to `do_science_setup`

2020-09-15 22:05 UTC, lspitler commented on scripts/dfw_manual_functions.py
> +    simulators=['weather', 'mount', 'power', 'night']
make arg to `do_science`

2020-09-15 22:05 UTC, lspitler commented on scripts/dfw_manual_functions.py
> +    simulators=['weather', 'power', 'night']
make arg

2020-09-15 22:09 UTC, wtgee commented
> @Physarah looking good. Not yet approving so can keep tweaking based upon improvements during the week. Can you incorporate what you learned last night into this file?
> 
> Also, it might just make sense to make this a script by adding the following at the bottom of the file:
> 
> ```
> python
> 
> def main(obstype,
>                 cam_name, 
>                 target_name, 
>                 initial_focus_position, 
>                 filter_type,
>                 num_sciobs=1,
>                 ...):
>     if obstype is "sci":
>         pocs_observation = do_science_setup(cam_name, 
>                                    target_name, 
>                                    initial_focus_position, 
>                                    filter_type)
>         for i in range(num_sciobs):
>              pocs_observation.observatory.observe()
>    elif obstype is "dark":
>         stuff
>    elif obstype is "flat":
>         stuff
> 
> if __name__ == '__main__':
>     parser = argparse.ArgumentParser()
>     parser.add_argument('--obs-type', type=str, help='Options: sci, dark, flat.', choices=["sci", "dark", "flat"])
>     parser.add_argument('--cam-name', type=str, help='Camera name in config.yaml to use.')
>     parser.add_argument('--filter', type=str, help='Valid filter name.')
>     parser.add_argument('--focus', type=int, help='The camera's best focus value.')
>     parser.add_argument('--target', type=str, help='Target to observe in targets.yaml.')
>     parser.add_argument('--num-sciobs', type=str, help='Number of science exposures to take.')
>     parser.add_argument('--exptime', type=str, help='Override default exptime.')
> 
>     args = parser.parse_args()
>     obstype = args.obstype
> 
>     main(meta_db_location)
> ```

We want to start writing scripts with [`click`](https://click.palletsprojects.com/en/7.x/) so it's good to get in the habit.  It's significantly easier.

2020-09-15 22:19 UTC, lspitler commented
> 
> We want to start writing scripts with [`click`](https://click.palletsprojects.com/en/7.x/) so it's good to get in the habit. It's significantly easier.

Ha, thanks for pointing this out. Looks useful.

2020-09-16 21:39 UTC, lspitler commented
@Physarah please push any and all changes you've implemented so far and ping me for review. thanks!

2020-10-28 02:07 UTC, closed without merging