Add coarse focus to evening calibrations
wtgee/huntsman-pocs pull request #75
Opened 2018-10-02 09:35 UTC by AnthonyHorton

Adds a coarse focus off all cameras to the evening calibration state, after flat fielding and nautical twilight, in order to implement the first item in #69.

Also took the opportunity to refactor the waiting for a specific Sun altitude into a utility function, and edited a few message strings ('sunset' -> 'twilight').

2018-10-02 09:45 UTC, wtgee requested changes
Hmm, a lot of the same thing is going on over here: https://github.com/panoptes/POCS/pull/541/files#diff-a318b148222fe28a50df3aa2824429fdR522. It's a little more convoluted over there as it is pulled into the pocs machinery itself and reads from the config.

It keeps the `pocs` objects out of utils file, which I think we should enforce. The `pocs` items are only used in state files as it is.

Can we just add the coarse focus after the flat-fielding for this PR and then we'll add in the appropriate wait after?

2018-10-02 09:53 UTC, AnthonyHorton commented
Ah, wasn't aware of the overlap with a WIP in POCS itself. Was just keen to make sure it was dark enough for the coarse focus to work, and felt I shouldn't just add a 3rd nearly identical `while` loop to `calibrating.py`. I would have just passed the `observatory` or `observer` to my utility function, but then I wouldn't be able to keep the `pocs.say`.

2018-10-02 10:06 UTC, AnthonyHorton commented
@wtgee Compromise temporary solution, move the `wait_for_sun_alt` utility function into `huntsman-pocs/states/calibrating.py` instead of `huntsman-pocs/utils/flats.py`?   Keeps the `pocs` object out of `utils` and avoids any overlap with the POCS WIP while providing the desired functionality in the meantime.  Once the WIP gets merged into POCS we can chuck this out of the `huntsman-pocs` state machine and use the new functions.  Going to want to do a bunch of that sort of thing anyway to stop `huntsman-pocs` duplicating functionality that's been added to POCS.

2018-10-02 11:04 UTC, AnthonyHorton commented
Doing some tinkering to get Travis and coverage working. Will spin out into a separate PR.

2018-10-02 20:52 UTC, wtgee approved these changes
LGTM although I see tests are failing.

2018-10-02 20:52 UTC, wtgee commented on states/huntsman/calibrating.py
> +        max_altitude is +90
`max_altitude = 90`

2018-10-03 00:35 UTC, AnthonyHorton commented on states/huntsman/calibrating.py
> +        max_altitude is +90
OK.

2018-10-03 00:45 UTC, AnthonyHorton commented
Passing now, thanks to #79!

2018-10-03 00:46 UTC, merged