Add missing dependency
wtgee/huntsman-pocs pull request #86
Opened 2018-10-18 21:20 UTC by wtgee

2018-10-18 22:06 UTC, lspitler approved these changes

2018-10-18 22:07 UTC, JAAlvarado-Montes approved these changes
It looks right

2018-10-18 22:08 UTC, lspitler requested changes
@wtgee I approved, but Travis is failing so I'm undo'ing the approve.

2018-10-20 23:21 UTC, lspitler approved these changes

2018-10-20 23:22 UTC, merged